apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::211116633177:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-U9PU6RsXqivj
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop


---
#service account:
# 1. create sa
# 2. create IAM role and attach permission
# 3. run pod with sa

# OIDC provider
# eksctl utils associate-iam-oidc-provider --cluster roboshop --approve

# eksctl create iamserviceaccount \
#   --name roboshop-secret-reader \
#   --namespace roboshop \
#   --cluster roboshop \
#   --attach-policy-arn arn:aws:iam::160885265516:policy/RoboshopMySQLSecretReader1 \
#   --approve